"""empty message

Revision ID: e050390210ef
Revises: 6a70fca74cc3
Create Date: 2021-06-21 19:58:14.032771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e050390210ef'
down_revision = '6a70fca74cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('Artist_id', sa.Integer(), nullable=False))
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Artist', ['Artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('shows', 'id')
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'Artist', ['artist_id'], ['id'])
    op.alter_column('shows', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('shows', 'Artist_id')
    op.drop_column('shows', 'Venue_id')
    # ### end Alembic commands ###
